### ISSUE TITLE
No error message is shown when selecting a non-existing machine

### ISSUE THREAD

**Issue by Colpocorto** [openMSX/openMSX#1337]
* openMSX version: 16.0-412-gf6ee2a4fc
* OS: Windows 7 X64
* Description of the issue: if openMSX is invoked via the command line and a machine whose configuration does not exist is selected, nothing happens. The emulator does not boot, and no error message is shown.

![image](https://user-images.githubusercontent.com/24856281/112700839-55730180-8e8f-11eb-973f-e8741b5f86aa.png)

**Comment by mthuurne** [comment]
Could this be an unintended consequence of #1326?

**Comment by m9710797** [comment]
Should be fixed now. But please verify.

**Comment by Colpocorto** [comment]
Partially fixed.
Stderr messages are shown now, but the program does not return to the console prompt correctly (the command prompt is not shown until I enter a new line).

https://user-images.githubusercontent.com/24856281/112718330-9c461300-8ef2-11eb-8bec-fb99947ffea5.mp4

**Comment by MBilderbeek** [comment]
Looks like openMSX returns directly and then a little while later the output is received. @peterhanraets is that expected?

**Comment by sdsnatcher73** [comment]
Yes that is how it works. There is no way to circumvent it in Windows with a GUI application. What could be done is create a wrapper openmsx.com (yes .com still exists in Windows). That wrapper would be a console application. It would also take precedence over openmsx.exe on the command line (if you just type openmsx). You could also prevent calling the .exe directly (by exiting in that check to attach to a console).

**Comment by Colpocorto** [comment]
Can't understand this.
This won't happen on the official 16.0 release.
Why is no way to circumvent it on the 16.0.414 build?

**Comment by MBilderbeek** [comment]
16.0 is a Windows console application. It means you always get also a terminal/commandprompt window when starting openMSX. @peterhanraets was trying to fix that. Apparently this is the consequence. How bad is this for you?

Also, @peterhanraets have you checked whether Catapult still works properly under Windows with this fix? I.e. do you get a list of machines and mappertypes still?

**Comment by Colpocorto** [comment]
> 16.0 is a Windows console application. It means you always get also a terminal/commandprompt window when starting openMSX. @peterhanraets was trying to fix that. Apparently this is the consequence. How bad is this for you?
> 

I don't think it's bad for me at all. But I sometimes make some workflows and automations that include launching openMSX from a .BAT or .CMD file so have to evaluate whether this has any impact yet. Probably not, or probably I will find a workaround if needed.

**Comment by MBilderbeek** [comment]
Can you do some quick tests whether it has impact? It would be good to know for such applications whether we can accept the current situation or whether we should try to find another way to solve it.

**Comment by Colpocorto** [comment]
@MBilderbeek  I've tested again and the issue does NOT happen if openMSX is launched inside a batch file (both on Powershell or cmd.exe).  It seems to be only a cosmetic thing if launched at the prompt, but nothing else.

This batch file:

    openmsx -v
    echo "ILOVEHINOTORI"

outputs this:

![image](https://user-images.githubusercontent.com/24856281/112731171-fb794700-8f35-11eb-97da-30de66f928c6.png)

**Comment by MBilderbeek** [comment]
OK, thanks, so if Catapult still works, we're good to go here.

**Comment by sdsnatcher73** [comment]
Where can I get a dev build of Catapult? Or how can I cross-compile one with mingw-w64?

**Comment by MBilderbeek** [comment]
@peterhanraets the Windows dev builds contain also Catapult builds. Do you also get a list of mapper types in Catapult? It's in the submenu ("Select ROM type") you get when you click on "Cart A" after selecting a ROM file. If you get a list there, it works.

**Comment by sdsnatcher73** [comment]
![image](https://user-images.githubusercontent.com/26295777/112750285-109eb600-8fc8-11eb-83d2-7bc849d5fdd4.png)
