### ISSUE TITLE
[Bug] Sony HBI-55 emulation bug [sf#536]

### ISSUE THREAD

**Issue by openMSX-import** [openMSX/openMSX#927]
**Reported by grauw on 2014-05-30 23:28 UTC**
When writing a value to HBI memory, it goes through the I8255 PPI IC, quote I8255.cc:

```
void I8255::outputPortC(byte value, EmuTime::param time)
{
    latchPortC = value;
    if (!(control & DIRECTION_C1)) {
        // output
        interface.writeC1(latchPortC >> 4, time);
    }
    if (!(control & DIRECTION_C0)) {
        // output
        interface.writeC0(latchPortC & 15, time);
    }
}
```

Note how the high nibble (writeC1) is output first, then the low nibble (writeC0).

Now, let’s look at MSXHBI55.cc:

```
void MSXHBI55::writeC0(nibble value, EmuTime::param /*time*/)
{
    writeLatch = (writeLatch & 0xF0) | value;
}
void MSXHBI55::writeC1(nibble value, EmuTime::param /*time*/)
{
    writeLatch = (writeLatch & 0x0F) | (value << 4);
    if (mode == 1) {
        sram->write(writeAddress, writeLatch);
    }
}
```

This code expects writeC0 to be called before writeC1 is called. But that’s not the case.

As a result, when I write 0D3H, it writes some other value. When I write 47H next, it will write 43H in stead, because it still uses the low nibble from the previous value.

Little test program:

```
10 OUT &HB3,&H80   ' configure PPI for write mode
20 OUT &HB0,&HC2   ' low address part
30 OUT &HB1,&H4A   ' = &H40 (write) + &H0A (high address part)
40 OUT &HB2,&HD3   ' the value to write
50 OUT &HB3,&H89   ' configure PPI for read mode
60 OUT &HB0,&HC2   ' low address part
70 OUT &HB1,&HCA   ' = &HC0 (read) + &H0A (high address part)
80 PRINT INP(&HB2) ' contents of &H0AC2
```

The output of this program should be 211 (0D3H). Note that due to the broken implementation, you need to run the program twice to get the correct result. Change line 40 to test a different value.

There’s also a more elaborate test program here: http://map.grauw.nl/resources/hbi55.php

By the way, the test program at the top of the MSXHBI55.cc listing contains this bit: “OUT &HB3,128-9_(I<>0)”. I’m not entirely clear as to why it does not output 137 when I is 0? I think it should always output 137, the “-9_(I<>0)” part should go. Otherwise, that should also do the trick.

I looked at the version history, it was broken since 2004 by 3a71a96.

**Comment by openMSX-import** [comment]
**Commented by grauw on 2014-05-31 00:31 UTC**
p.s. You can write some unit tests calling writeIO() / readIO() to verify the fix :).

**Comment by openMSX-import** [comment]
**Commented by m9710797 on 2014-05-31 07:55 UTC**
Thanks for your report!

Swapping C0/C1 (in either I8255 or MSXHBI55), would 'fix' the symptom. Though it still won't work if port C is set half as input, half as output.

I wonder what happens on a real HBI55 in this scenario. When a nibble is set as input, the PPI makes the corresponding pins high impedance. I very much doubt the HBI55 will have pull-up (or -down) resistors attached to these pins because in normal circumstances they aren't needed. So, I think, it depends on the PPI whether '0's, '1' or random bits are written to the corresponding nibble in RAM that was set to input.

@Laurens: You've already investigated enough to fix the 'normal' HBI55 use case. It would be nice if you could also investigate how this 'unusual' case behaves. Thanks!

BTW: If I had to _guess_ I'd say the nibble that was set as input behaves as-if you wrote 0b1111 to it. Laurens, if you can confirm this, that'll allow some simplifications in our current PPI emulation.

**Comment by openMSX-import** [comment]
**Commented by grauw on 2014-05-31 13:45 UTC**
    10 ' Unit test 1, writing nibbles
    11 M=&H80:O=1:A=&H11:EX=&H11:GOSUB 100
    12 M=&H81:O=1:A=&H22:EX=&H21:GOSUB 100
    13 M=&H88:O=1:A=&H33:EX=&H23:GOSUB 100
    14 M=&H89:O=1:A=&H44:EX=&H23:GOSUB 100
    20 ' Unit test 2, uses last output value
    21 M=&H80:O=1:A=&H11:EX=&H11:GOSUB 100
    22 M=&H80:O=2:A=&H99:EX=&H99:GOSUB 100
    23 M=&H81:O=1:A=&H22:EX=&H29:GOSUB 100
    30 ' Unit test 3, something's funny with address 0!
    31 M=&H80:O=0:A=&H11:EX=&H01:GOSUB 100
    32 M=&H81:O=0:A=&H22:EX=&H21:GOSUB 100
    33 M=&H88:O=0:A=&H33:EX=&H23:GOSUB 100
    34 M=&H89:O=0:A=&H44:EX=&H23:GOSUB 100
    40 END
    100 OUT &HB3,M
    110 OUT &HB0,O
    120 OUT &HB1,&H40
    130 OUT &HB2,A
    140 OUT &HB3,&H89
    150 OUT &HB0,O
    160 OUT &HB1,&HC0
    170 I=INP(&HB2)
    180 IF EX <> I THEN PRINT "Expected:";EX;", was:";I
    190 RETURN
    run
    Ok

So, it remembers the last output value and just changes the bits that are in output mode. I imagine the bit-set command does the same thing.

Note the third test, when I use O=0 in stead of 1 the return value is not the value I just set! I guess that explains the <> 0 in BIFI’s test, there’s something going on there.

**Comment by openMSX-import** [comment]
**Commented by m9710797 on 2014-06-01 19:29 UTC**
Fixed in revision 523a56eda.
The original test case now passes. The 2nd test passes part 1 and part2 but not part 3. So there is indeed something funny with address 0 :-)

Shall we leave this bug report open for the address 0 stuff? Or should we create a separate one?

@Laurens: Very nice article about HBI55 on http://map.grauw.nl. Though I think there's a mistake in the table for port B bit 7, read and write are swapped.

**Comment by openMSX-import** [comment]
**Commented by grauw on 2014-06-01 19:46 UTC**
Thanks, table is fixed :).

**Comment by MBilderbeek** [comment]
A bit late, but it looks like these changes broke the test program for address 0 as well.
```
10  FOR I=0 TO 4095: OUT &HB3,128: OUT &HB0,I MOD 256: OUT &HB1,64 OR I\256: OUT &HB2,I MOD 256: NEXT I
20  FOR I=0 TO 4095:OUT &HB3,128-9*(I<>0): OUT &HB0,I MOD 256: OUT &HB1,192 OR I\256: IF I MOD 256=INP(&HB2) THEN NEXT ELSE PRINT "Error comparing byte:";I;"expected ";IMOD256;"got ";INP(&HB2): NEXT
30  PRINT "Done!"
```
now gives:
`Error comparing byte: 0 expected  0 got  255`

**Comment by grauw** [comment]
### Correct way of writing by pulsing chip select

```
10 OUT &HB1,0:OUT &HB3,&H80
20 FOR I=0 TO 15:OUT &HB2,I:OUT &HB0,I:OUT &HB1,&H40:OUT &HB1,0:NEXT
10 OUT &HB1,0:OUT &HB3,&H89
40 FOR I=0 TO 15:OUT &HB0,I:OUT &HB1,&HC0:?INP(&HB2);:OUT &HB1,&H80:NEXT
```

Output: `0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15`

### Do not pulse chip select while reading, so OE and CS stay active

```
10 OUT &HB1,0:OUT &HB3,&H80
20 FOR I=0 TO 15:OUT &HB2,I:OUT &HB0,I:OUT &HB1,&H40:OUT &HB1,0:NEXT
10 OUT &HB1,0:OUT &HB3,&H89
40 FOR I=0 TO 15:OUT &HB0,I:OUT &HB1,&HC0:?INP(&HB2);:NEXT
```

Output: `0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15`

Shows that reading is continuous while OE and CS are active.

### Do not pulse chip select while writing, so WE and CS stay active

```
10 OUT &HB1,0:OUT &HB3,&H80
20 FOR I=0 TO 15:OUT &HB2,I:OUT &HB0,I:OUT &HB1,&H40:NEXT
10 OUT &HB1,0:OUT &HB3,&H89
40 FOR I=0 TO 15:OUT &HB0,I:OUT &HB1,&HC0:?INP(&HB2);:NEXT
```

Output: `1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 15`

Shows that writing is continuous while OE and CS are active.

### Pulling the line that sets CS / WE / OE out of the loop

Effectively identical to the previous test.

```
10 OUT &HB1,0:OUT &HB3,&H80:OUT &HB1,&H40
20 FOR I=0 TO 15:OUT &HB2,I:OUT &HB0,I:NEXT
10 OUT &HB1,0:OUT &HB3,&H89
40 FOR I=0 TO 15:OUT &HB0,I:OUT &HB1,&HC0:?INP(&HB2);:NEXT
```

Output: `1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 15`

### Changing the address LSB (port A) before the data (port C)

```
10 OUT &HB1,0:OUT &HB3,&H80:OUT &HB1,&H40
20 FOR I=0 TO 15:OUT &HB0,I:OUT &HB2,I:NEXT
10 OUT &HB1,0:OUT &HB3,&H89
40 FOR I=0 TO 15:OUT &HB0,I:OUT &HB1,&HC0:?INP(&HB2);:NEXT
```

Output: `0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15`

Will still go wrong if the address MSB changes.

### Setting port C to read (no / floating output) while write is still enabled

```
10 OUT &HB1,0:OUT &HB3,&H80
20 FOR I=0 TO 15:OUT &HB2,I:OUT &HB0,I:OUT &HB1,&H40:NEXT
10 OUT &HB3,&H89:OUT &HB1,0
40 FOR I=0 TO 15:OUT &HB0,I:OUT &HB1,&HC0:?INP(&HB2);:NEXT
```

Output: `7, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 15`

The first byte is corrupted by setting the PPI port C direction to input before disabling write. I presume it’s writing a floating value. Not sure why it affects the first byte though, at this point the address LSB (in 0B0H) should still be 15…?

**Comment by grauw** [comment]
While chip select and write enable are active, the SRAM is written continuously. While the chip select and output enable are active, the SRAM is read continuously. This means that address and data line changes have an immediate effect.

p.s. I updated the [HBI-55 MAP article](http://map.grauw.nl/resources/hbi55.php).

**Comment by grauw** [comment]
> The first byte is corrupted by setting the PPI port C direction to input before disabling write. I presume it’s writing a floating value. Not sure why it affects the first byte though, at this point the address LSB (in 0B0H) should still be 15…?

PPI documentation says that all output registers reset (to 0, I presume) when its mode is changed (btw, not emulated by I8255.cc). But if that is the case then one would expect it shouldn’t be writing.

However the write cycle diagram of [the SRAM chip](https://datasheet.datasheetarchive.com/originals/distributors/Datasheets-112/DSAP0047038.pdf) does specify that the DATA IN signals must stay stable for `tDH` (Data Hold from Write Time) time. I think this delay causes it to still write whatever’s on the data / address lines for a short while after CS / WE go inactive.

**Comment by m9710797** [comment]
> PPI documentation says that all output registers reset (to 0, I presume) when its mode is changed (btw, not emulated by I8255.cc)...

This is unclear (to me). I checked the datasheets of several PPI-compatible chips:
- Intersil 82C55A mentions: .. any port programmed as an output port is initialized to all zeros when the control word is written.
- OKI Semiconductor MSM82C55A (this is the variant used in HBI-55) mentions: .. the output registers for port A and C are cleared to 0 each time data is written in the command register and the mode is changed, but the port B state is undefined.
- But many other datasheet don't mention anything at all about this behavior, even though the wording in surrounding paragraphs is often identical to the above datasheets.

I wonder if this clear-to-zero is a universal feature. So only a difference in documentation or really a functional difference between PPI variants.

**Comment by grauw** [comment]
I see. I was basing this on what I read in http://map.grauw.nl/resources/ppi/intel_82c55a.pdf (page 5):

> All of the output registers, including the status flip-flops, will be reset whenever the mode is changed.

If there is no reset at all, I can’t explain why it would write to memory location 0 (port A). If port B is not cleared by the OKI chip, that could be a better explanation for why it still does the write than the one that I offered involving `tDH`.

**Comment by m9710797** [comment]
I've pushed a fix:
* Grauw's test programs (2022/02/20) now work fine. Except for the last one that outputs: **1** 2 3 .. 15 15.
* Grauw's tests of 2015/06/24 also work fine, except for the test on line 31.
I believe that MBilderbeek's test (2022/01/24) is invalid (undefined behavior?). It shows a lot of failures. Does this test run on a real MSX?

The issue with reset port A, C (and B) to 0 on a PPI mode change is still open. This first needs more investigation.

**Comment by grauw** [comment]
Quote `MSXHBI55::writeStuff` and `MSXHBI55:readStuff` (🙂):

> ```
> if ((B & 0x40) == 0) {
> 	// /CE of RAM chip(s) not active
> 	return;
> }
> ```

Per the schematic, non-zero bits 4-5 also cause CE to be not active.

```
if ((B & 0x70) != 0x40)
```

Would cover that.

> ```
> // When port C is (partially) set as input, we technically use a
> // 'floating value'. Hack: experiments have shown that we more
> // closely _approximate_ this (invalid) case by using the last
> // written (output-)value.
> ```

If this refers to the [discussion](https://github.com/openMSX/openMSX/issues/1209#issuecomment-1042325725) for switched I/O ports on the Mitsubishi ML-8000 and Sanyo MPC-3, I think it is important to distinguish that these experiments have not been done on the HBI-55, and it should not be assumed that the same behaviour applies to the HBI-55.

In the case of the prior discussion there was a very short time between when the bus started floating and when it was read, whereas in this case there’s no real way to tell how long the bus has been floating. E.g. the BASIC test program leaves it floating a (relatively) very long time, and I don’t believe it would still be read as the last value written to PPI port C after so much time. As supporting evidence; the previously written value in the last test was 15, but address 0 ends up with the value 7.

> ```
> // TODO investigate this further.
> ```
> ```
> return 255; // TODO check this
> ```

Can you list what still needs to be tested exactly, and how I could test it?

Having tests to type in would be even better 😉.

**Comment by m9710797** [comment]
Thanks! I've fixed the /CE stuff.

I know the floating stuff is just an approximation. It better than nothing and good enough for small test programs like these. Maybe not even worth trying to get fully correct.
That last TODO is also related to floating values I think.  It's the value you read when you program port A/B as input and then read it. Maybe also not worth spending time on?

If you want to continue investigating then maybe check the reset-to-zero-on-mode-switch behavior of the PPI. I wonder if the regular PPI inside a MSX shows this behavior? Maybe only when it's a discrete chip and not when integrated in a MSX-engine?

Anyway, thanks a lot for your help!

**Comment by MBilderbeek** [comment]
> I believe that MBilderbeek's test (2022/01/24) is invalid (undefined behavior?). It shows a lot of failures. Does this test run on a real MSX?

Well, it isn't my test. It was in the source code in `src/memory/MSXHBI55.cc`. Can you check this test on the real hardware, @grauw ?

@m9710797 The test by saving a program to the SRAM is still failling for me:
1. Start openMSX with Sony HB-75P and Sony HBI-55
2. Choose "BASIC + DATA CARTRIDGE" and press Enter
3. Type in a simple basic program and type `SAVE"CAT:TEST`
4. Reset the MSX
5. As step 2
6. Type in: `LOAD"CAT:TEST`
7. Result: `Direct statement in file`, instead of successful load.

**Comment by m9710797** [comment]
Ok, fixed stupid bug.
@MBilderbeek: it should work now.

**Comment by MBilderbeek** [comment]
@m9710797 The first time I tried it, I still got an error after loading. But I can't reproduce that anymore.... so, I don't know what happened. It seems to work now. Thanks for fixing this issue after 8 years :smiley:

**Comment by m9710797** [comment]
Same here. First time I tested I thought I failed to fix the bug. (All) later times it worked fine.
I _guess_ it's because of the SRAM content that was written by earlier versions?
